create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table ticket (raffleStatus integer, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
create table user (id bigserial not null, email varchar(255), lname varchar(255), name varchar(255), pwd varchar(255), role varchar(255), primary key (id));
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table roles (id serial not null, name varchar(255), primary key (id));
create table ticket (raffleStatus integer not null, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
create table user_entity (id bigserial not null, email varchar(255), lname varchar(255), name varchar(255), pwd varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id bigint not null);
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FK6y02653x6ebhsu2plf21ard62 foreign key (user_id) references user_entity;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table roles (id serial not null, name varchar(255), primary key (id));
create table ticket (raffleStatus integer not null, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
create table user_entity (id bigserial not null, email varchar(255), lname varchar(255), name varchar(255), pwd varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id bigint not null);
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FK6y02653x6ebhsu2plf21ard62 foreign key (user_id) references user_entity;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table roles (id serial not null, name varchar(255), primary key (id));
create table ticket (raffleStatus integer not null, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
create table user_entity (id bigserial not null, email varchar(255), lname varchar(255), name varchar(255), pwd varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id bigint not null);
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FK6y02653x6ebhsu2plf21ard62 foreign key (user_id) references user_entity;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table roles (id serial not null, name varchar(255), primary key (id));
create table ticket (raffleStatus integer not null, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
create table user_entity (id bigserial not null, email varchar(255), lname varchar(255), name varchar(255), pwd varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id bigint not null);
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FK6y02653x6ebhsu2plf21ard62 foreign key (user_id) references user_entity;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table roles (id serial not null, name varchar(255), primary key (id));
create table ticket (raffleStatus integer not null, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
create table user_entity (id bigserial not null, email varchar(255), lname varchar(255), name varchar(255), pwd varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id bigint not null);
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FK6y02653x6ebhsu2plf21ard62 foreign key (user_id) references user_entity;
create table raffle (date date, disc float(53), price float(53), id bigserial not null, descr varchar(255), event varchar(255), name varchar(255), primary key (id));
create table roles (id serial not null, name varchar(255), primary key (id));
create table ticket (raffleStatus integer not null, number bigint not null, raffle_id bigint not null, city varchar(255) not null, primary key (number, raffle_id, city));
create table user_entity (id bigserial not null, email varchar(255), lname varchar(255), name varchar(255), pwd varchar(255), primary key (id));
create table user_roles (role_id integer not null, user_id bigint not null);
alter table if exists ticket add constraint FKsnctcvbosfhux3gc5iobqpurs foreign key (raffle_id) references raffle;
alter table if exists user_roles add constraint FKh8ciramu9cc9q3qcqiv4ue8a6 foreign key (role_id) references roles;
alter table if exists user_roles add constraint FK6y02653x6ebhsu2plf21ard62 foreign key (user_id) references user_entity;
